const express = require('express');
const router = express.Router();

const restaurants = require('./restaurants');
const pedidos = require('./pedidos');
const auth = require('./auth');
const sucursales = require('./sucursales');
const secciones = require('./secciones');
const mesas = require('./mesas');
const categorias = require('./categorias');
const productos = require('./productos');
const productoPrecios = require('./producto_precios');
const modificadores = require('./modificadores');
const pedidosDetalles = require('./pedidos_detalles');
const clientes = require('./clientes');
const cuentas = require('./cuentas');
const comprobantes = require('./comprobantes');
const pagos = require('./pagos');
const metodosPago = require('./metodos_pago');
const caja = require('./caja');
const historial = require('./historial');
const usuarios = require('./usuarios');
const cocina = require('./cocina');
const impresoras = require('./impresoras');
const printAgent = require('./print_agent');
const recetas = require('./recetas');
const reportes = require('./reportes');

router.use('/restaurants', restaurants);
router.use('/pedidos', pedidos);
router.use('/auth', auth);
router.use('/sucursales', sucursales);
router.use('/secciones', secciones);
router.use('/mesas', mesas);
router.use('/categorias', categorias);
router.use('/productos', productos);
router.use('/producto_precios', productoPrecios);
router.use('/modificadores', modificadores);
router.use('/pedidos_detalles', pedidosDetalles);
router.use('/clientes', clientes);
router.use('/cuentas', cuentas);
router.use('/comprobantes', comprobantes);
router.use('/pagos', pagos);
router.use('/metodos_pago', metodosPago);
router.use('/caja', caja);
router.use('/historial', historial);
router.use('/usuarios', usuarios);
router.use('/cocina', cocina);
router.use('/impresoras', impresoras);
router.use('/print-agent', printAgent);
router.use('/recetas', recetas);
router.use('/reportes', reportes);

module.exports = router;
